### PR TITLE
Better 1.16 support

### PR DESCRIPTION
**Pull request by Geolykt**
This will make some severe changes to the way enchantments are read and written, however I will attempt my best at making this the most downwards compatible. With this changed, nothing stands in the way of support for 1.16.x
If you have better algorithms for solving the issues, feel free to give some opinions, thoughts and contribute to the PR in other ways.
I hope to finish this by the end of this weekend, but it could easily take longer.

### CODE REVIEW

**Comment by Geolykt** [comment]
And it's done, now we only need to add backwards compatibillity and we should be good to go

**Comment by Geolykt** [comment]
I'm not 100% sure that this will always work, but it should be sufficent enough to run.
Backwards compatibillity needs to be tested though.

It is likely already well optimised, but if you have suggestions on how to make it run better, then please come forward.

**Comment by Jeradone** [comment]
This does not work with 1.16.2 for some reason, I cant use any of the enchants

**Comment by Geolykt** [comment]
@Jeradone that is pretty vague, but I will attempt to recreate it using spigot 1.16.2. Craftbukkit isn't supported (duh) and Paper tests aren't performed by me, neither will I perform any attempt at creating compatibillity with Paper. I assume this occoured because I use slightly different settings from normal for debug purposes, so I will try that.
Thanks anyways

**Comment by Geolykt** [comment]
You seem to be right, while old items appear to be still inteact, newer items aren't. I'll change that now

**Comment by Geolykt** [comment]
@Jeradone Could you look at it again?

**Comment by Jeradone** [comment]
What am I looking for again? I am using speed boots rn and its not working
as well.

>

**Comment by Geolykt** [comment]
They work for me, how old are the boots? Like, are they new or are they from before the conversion? And do you get the Item Converted log just once or spammed, and are you using the compiled version with the latest git commit of 6856509?

**Comment by Jeradone** [comment]
So I just enchanted my boots in my survival, and apparently nothing has
changed, I have meador on my boots and I am not gaining speed nor a jump
boost, I am playing 1.16.2

**Comment by Geolykt** [comment]
Well, sorry for being somewhat late (github at it's finest), I  got no clue what (didn't) happen here

**Comment by Jeradone** [comment]
Im so confused, do the enchantments work?

**Comment by Geolykt** [comment]
What I'm saying is that it works in my Testing Environment, and even my Fork  runs without issues (although I only provided the Download yesterday), but I would've got an issue by now especially since it's using the Same Code now.


Where die you get the Plugin jar from?

**Comment by Jeradone** [comment]
I got it from my.server pros plugin list.

**Comment by Geolykt** [comment]
Oh god. Well, firstly, this is the wrong place to post, this is a Pull Request, not an issue.
Secondly, if you got no idea on how to build the code, then please don't comment on it unless you believe it adds value to the current conversation or you see fundemental flaws (like malicious code), but chances are that you aren't going to spot them if you don't know how to build it.
Thirdly, if you wish to obtain a neatly packaged jar file that is based on this PR (along other things), then go to https://github.com/Geolykt/NMSless-Zenchantments/releases

**Comment by Geolykt** [comment]
I think the last commit should fix the last few bugs that I had with the code

**Comment by Geolykt** [comment]
I'll be working on rewriting the code, that is if it's needed. (I got no idea if the code that was just pushed actually fixes the current issues)

**Pull request closed without merging**
